--liquibase formatted sql

--changeset vadim:1
CREATE TABLE IF NOT EXISTS users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(64)      NOT NULL,
    email               VARCHAR(64)      NOT NULL UNIQUE,
    age                 INT              NOT NULL,
    weight              INT              NOT NULL,
    height              INT              NOT NULL,
    goal                VARCHAR(32)      NOT NULL,
    daily_calories_norm DOUBLE PRECISION NOT NULL
);

--changeset vadim:2
CREATE TABLE IF NOT EXISTS meal
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(128)     NOT NULL,
    calories DOUBLE PRECISION NOT NULL,
    proteins DOUBLE PRECISION NOT NULL,
    carbs    DOUBLE PRECISION NOT NULL,
    fats     DOUBLE PRECISION NOT NULL
);

--changeset vadim:3
CREATE TABLE IF NOT EXISTS food_in_take
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date           DATE,
    meal_type      VARCHAR(32)      NOT NULL,
    total_calories DOUBLE PRECISION NOT NULL,
    user_id        BIGINT           NOT NULL REFERENCES users (id)
);

--changeset vadim:4
CREATE TABLE IF NOT EXISTS food_in_take_meals
(
    food_in_take_id BIGINT NOT NULL REFERENCES food_in_take (id),
    meal_id         BIGINT NOT NULL REFERENCES meal (id),
    PRIMARY KEY (food_in_take_id, meal_id)
)