--liquibase formatted sql

--changeset vadim:1
--comment: Create core users table with basic profile information
CREATE TABLE IF NOT EXISTS users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(64)      NOT NULL,
    email              VARCHAR(64)      NOT NULL UNIQUE,
    age                INT              NOT NULL,
    weight             INT              NOT NULL,
    height             INT              NOT NULL,
    goal               VARCHAR(32)      NOT NULL,
    daily_calories_norm DOUBLE PRECISION NOT NULL
);
--rollback:"DROP TABLE users"

--changeset vadim:2
--comment: Add table and column comments for users
COMMENT ON TABLE users IS 'Stores user profile information and fitness goals';
COMMENT ON COLUMN users.id IS 'Primary key, auto-incremented';
COMMENT ON COLUMN users.name IS 'Full name of the user';
COMMENT ON COLUMN users.email IS 'Unique email address for authentication';
COMMENT ON COLUMN users.age IS 'Age in years (14-115)';
COMMENT ON COLUMN users.weight IS 'Weight in kilograms (10-400)';
COMMENT ON COLUMN users.height IS 'Height in centimeters (40-220)';
COMMENT ON COLUMN users.goal IS 'Fitness goal: WEIGHT_LOSS, MAINTENANCE, MUSCLE_GAIN';
COMMENT ON COLUMN users.daily_calories_norm IS 'Daily calorie norm calculated using Harris-Benedict formula';

--changeset vadim:3
--comment: Create meal table with nutritional information
CREATE TABLE IF NOT EXISTS meal
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(128)     NOT NULL,
    calories DOUBLE PRECISION NOT NULL,
    proteins DOUBLE PRECISION NOT NULL,
    carbs    DOUBLE PRECISION NOT NULL,
    fats     DOUBLE PRECISION NOT NULL
);
--rollback:"DROP TABLE meal"

--changeset vadim:4
--comment: Add table and column comments for meals
COMMENT ON TABLE meal IS 'Contains nutritional information about meals';
COMMENT ON COLUMN meal.id IS 'Primary key, auto-incremented';
COMMENT ON COLUMN meal.name IS 'Name/description of the meal';
COMMENT ON COLUMN meal.calories IS 'Calories per serving (kcal)';
COMMENT ON COLUMN meal.proteins IS 'Protein content per serving (grams)';
COMMENT ON COLUMN meal.carbs IS 'Carbohydrates per serving (grams)';
COMMENT ON COLUMN meal.fats IS 'Fats per serving (grams)';

--changeset vadim:5
--comment: Create food intake records table
CREATE TABLE IF NOT EXISTS food_in_take
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date           DATE,
    meal_type      VARCHAR(32)      NOT NULL,
    total_calories DOUBLE PRECISION NOT NULL,
    user_id        BIGINT           NOT NULL REFERENCES users (id)
);
--rollback:"DROP TABLE food_in_take"

--changeset vadim:6
--comment: Add table and column comments for food intake
COMMENT ON TABLE food_in_take IS 'Records of user meal consumption';
COMMENT ON COLUMN food_in_take.id IS 'Primary key, auto-incremented';
COMMENT ON COLUMN food_in_take.date IS 'Date when meals were consumed';
COMMENT ON COLUMN food_in_take.meal_type IS 'Type: BREAKFAST, LUNCH, DINNER, SNACK';
COMMENT ON COLUMN food_in_take.total_calories IS 'Sum of calories from all meals in this intake';
COMMENT ON COLUMN food_in_take.user_id IS 'Foreign key to users table';

--changeset vadim:7
--comment: Create junction table for food intake and meals (many-to-many)
CREATE TABLE IF NOT EXISTS food_in_take_meals
(
    food_in_take_id BIGINT NOT NULL REFERENCES food_in_take (id),
    meal_id         BIGINT NOT NULL REFERENCES meal (id),
    PRIMARY KEY (food_in_take_id, meal_id)
);
--rollback:"DROP TABLE food_in_take_meals"

--changeset vadim:8
--comment: Add table and column comments for junction table
COMMENT ON TABLE food_in_take_meals IS 'Junction table for many-to-many relationship between food intake and meals';
COMMENT ON COLUMN food_in_take_meals.food_in_take_id IS 'Foreign key to food_in_take table';
COMMENT ON COLUMN food_in_take_meals.meal_id IS 'Foreign key to meal table';